# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('favorite_color', models.CharField(max_length=200)),
                ('favorite_fruit', models.CharField(max_length=200)),
                ('catch_phrase', models.CharField(max_length=200)),
            ],
        ),
    ]
